### ISSUE TITLE
No button visible on tasks tab bar

### ISSUE THREAD

**Issue by AntwerpPeter** [sigurd-dev/Thunderbird-Google-Messages-Tab#1]
Version 1.0.0. from 03/08/2021 installed via Thunderbird add-ons website.
https://addons.thunderbird.net/en-US/thunderbird/addon/google-messages-tab
Thunderbird 78.12.0 (32-bit)
After installation there is no button to open the Google Messages Tab visible

**Comment by sigurd-dev** [comment]
Please check Main toolbar under inbox. Also make sure Main Toolbar is visible. Tested in Linux and Windows, version 78.12.0 (64-bit)

**Comment by AntwerpPeter** [comment]
I have upgraded to TB 64 bit and now it works.
